#!/usr/bin/env bash
#  displays the content of the file /etc/passwd as a story

while IFS=":" read USERNAME PASSWORD USER_ID GROUP_ID USER_ID_INFO HOME_DIRECTORY COMMAND_SHELL; do
    echo "The user  is part of the  gang, lives in  and rides . 's place is protected by the passcode , more info about the user here: "
done < /etc/passwd
