#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

HOUR=0
while [ "" -lt 13 ]; do
    echo "Hour: "
    MINUTE=1
    while [ "" -lt 60 ]; do
echo ""
let MINUTE=MINUTE+1
    done
    let HOUR=HOUR+1
done
